name: PR Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml

  integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
    secrets:
      OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  e2e-tests:
    uses: ./.github/workflows/run-e2e-tests.yml
    secrets:
      OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
